#!lua

--[[
Usage: 
	windows: premake5.exe --os=windows vs2015
	linux:  premake5.exe --os=linux gmake
]]

require("conanpremake")  -- generated by conan

workspace "GrpcExamplesCpp"
	location (_ACTION)  -- subdir vs2015 (or gmake, ...)
	configurations { "Release", "Debug" }
	platforms { "x64", "x32" }
	language "C++"
	flags {
		"C++11",
	}

	filter "configurations:Debug"
		flags { "Symbols" }
		defines { "DEBUG" }
	filter "configurations:Release"
		defines { "NDEBUG" }
		optimize "On"
	filter "system:windows"
		defines {
			"_WIN32_WINNT=0x0600"  -- i.e. Windows 7 target
		}
	filter {}

	includedirs { conan_includedirs }
	libdirs { conan_libdirs }
	links { conan_libs }

group "helloworld"

project "greeter_client"
	kind "ConsoleApp"
	files { "helloworld/helloworld*.*", "helloworld/greeter_client.*" }
project "greeter_server"
	kind "ConsoleApp"
	files { "helloworld/helloworld*.*", "helloworld/greeter_server.*" }
project "greeter_async_client"
	kind "ConsoleApp"
	files { "helloworld/helloworld*.*", "helloworld/greeter_async_client.*" }
project "greeter_async_client2"
	kind "ConsoleApp"
	files { "helloworld/helloworld*.*", "helloworld/greeter_async_client2.*" }
project "greeter_async_server"
	kind "ConsoleApp"
	files { "helloworld/helloworld*.*", "helloworld/greeter_async_server.*" }
  
group "route_guide"

project "route_guide_client"
	kind "ConsoleApp"
	files { "route_guide/**" }
	removefiles { "route_guide/*_server.*" }
project "route_guide_server"
	kind "ConsoleApp"
	files { "route_guide/**" }
	removefiles { "route_guide/*_client.*" }

group ""  -- End of group


